#!/bin/bash

../cross/bin/i686-elf-as bootstrap.asm -o boot.o
../cross/bin/i686-elf-gcc -c kernel.c -okernel.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra
../cross/bin/i686-elf-gcc -c string.c -ostring.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra
../cross/bin/i686-elf-gcc -T linker.ld -o myos.bin -ffreestanding -O2 -nostdlib boot.o kernel.o string.o -lgcc
if grub-file --is-x86-multiboot myos.bin; then
  echo multiboot confirmed
else
  echo the file is not multiboot
fi